### ISSUE TITLE
Show detailed explanations for errors (in debug mode)

### ISSUE THREAD

**Issue by hnkb** [labandierra/junior#24]
- [ ] Only show error and warning windows when executing a program compiled in Debug mode
- [ ] Display warnings (not errors) only once per execution
- [ ] In `window::_create()`, when creation of class or window is unsuccessful, alert user
- [ ] In draw functions, when window is invalid (already deleted). Is it possible?
- [ ] In simple API, when user tries to draw without creating a window first. See #23 
- [ ] When user calls `begin_draw()`, but after a long time (maybe 1s timeout) doesn’t call `end_draw()`. See #4 
- [ ] When each `begin_draw()` call is not matched with a `end_draw()`. See #4 
- [ ] ... what more?
